spring:
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/api/unir/auth/**
          filters:
            - StripPrefix=2

        - id: ProfileService_Profile
          uri: lb://ProfileService
          predicates:
            - Path=/api/unir/profile/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: ProfileService_Company
          uri: lb://ProfileService
          predicates:
            - Path=/api/unir/company/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: ProfileService_Education
          uri: lb://ProfileService
          predicates:
            - Path=/api/unir/education/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: PostService_Post
          uri: lb://PostService
          predicates:
            - Path=/api/unir/post/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: PostService_Likes
          uri: lb://PostService
          predicates:
            - Path=/api/unir/likes/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: ConnectionsService
          uri: lb://ConnectionsService
          predicates:
            - Path=/api/unir/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
