spring:

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5174
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-User-Id
            allowCredentials: true

      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/api/unir/auth/**
          filters:
            - StripPrefix=2

        - id: ProfileService_Profile
          uri: lb://ProfileService
          predicates:
            - Path=/api/unir/profile/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: ProfileService_Company
          uri: lb://ProfileService
          predicates:
            - Path=/api/unir/company/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: ProfileService_Institution
          uri: lb://ProfileService
          predicates:
            - Path=/api/unir/institution/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: ProfileService_Education
          uri: lb://ProfileService
          predicates:
            - Path=/api/unir/education/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: PostsService
          uri: lb://PostsService
          predicates:
            - Path=/api/unir/posts/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: ConnectionService
          uri: lb://ConnectionService
          predicates:
            - Path=/api/unir/connections/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: SubscriptionService_Payments
          uri: lb://SubscriptionService
          predicates:
            - Path=/api/unir/payments/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: SubscriptionService_Subscriptions
          uri: lb://SubscriptionService
          predicates:
            - Path=/api/unir/subscriptions/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: NotificationService
          uri: lb://NotificationService
          predicates:
            - Path=/api/unir/notifications/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: SubscriptionService_Webhook
          uri: lb://SubscriptionService
          predicates:
            - Path=/api/unir/webhook/**
          filters:
            - StripPrefix=2

        - id: chat-service
          uri: lb://CHATSERVICE
          predicates:
            - Path=/api/unir/messages/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: video-call-service
          uri: http://localhost:5002
          predicates:
            - Path=/api/unir/video/**
          filters:
            - RewritePath=/api/unir/video/(?<segment>.*), /$\{segment}

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
