spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: NotificationService
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.rishbootdev.*